- name: sample play
  hosts: localhost
  become: yes
  tasks:
    - name: Task with Tag dev
      ansible.builtin.debug:
        msg: Hello DEV
      tags:
        - dev
    - name: Task with Tag qa
      ansible.builtin.debug:
        msg: Hello QA
      tags:
        - qa
      