- name: sample play
  hosts: localhost
  become: yes
  tasks:
    - name: Task with Tag dev
      ansible.builtin.debug:
        msg: Hello DEV
      tags:
        - dev
      notify: 
        - dev handler # here handler will not be called because state is not changed

    - name: Task with Tag qa
      ansible.builtin.debug:
        msg: Hello QA
      tags:
        - qa
      notify:
        - qa hanlder  # here handler will not be called because state is not changed

  handlers:
    - name: dev handler
      ansible.builtin.debug:
        msg: Dev Hanlder is called by task with Tag DEV
    
    - name: qa handler
      ansible.builtin.debug:
        msg: QA Handler is called by task with Tag QA
      