- name: this will copy demo.cnf from files folder to destination
  ansible.builtin.copy:
    src: demo.cnf
    dest: /tmp
  tags:
    - copy
  notify:
    - copy handler

- name: this will copy demo-template.cnf from files by adding dynamic values to it
  ansible.builtin.template:
    src: demo-template.cnf.j2
    dest: /tmp/demo-template.cnf
  tags:
    - template
  notify:
    - template handler
  
